[package]
name = "vim_key"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27"
pest = "2"
pest_derive = "2"
log = "0.4"
